<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.18362.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
	<WindowsPackageType>None</WindowsPackageType>
	<Platforms>AnyCPU;ARM64;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="image.jpg" />
    <None Remove="image2.png" />
    <None Remove="SqueezeNet.Labels.txt" />
    <None Remove="SqueezeNet.onnx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="image.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="image2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="SqueezeNet.Labels.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqueezeNet.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.AI.MachineLearning" Version="2.2.12" />
  </ItemGroup>

	<Target Name="RemoveUnusedWindowsMLBinaries" AfterTargets="Build">
		<ItemGroup>
			<_UnusedDirectML Include="$(OutDir)DirectML.dll" Condition="Exists('$(OutDir)DirectML.dll')" />
			<_UnusedDirectML Include="$(OutDir)runtimes\win-*\native\DirectML.dll" />
		</ItemGroup>
		<Delete Files="@(_UnusedDirectML)" />
	</Target>

	<Target Name="RemoveUnusedWindowsMLBinariesFromPublish" AfterTargets="Publish">
		<ItemGroup>
			<_UnusedDirectMLPublish Include="$(PublishDir)DirectML.dll" Condition="Exists('$(PublishDir)DirectML.dll')" />
			<_UnusedDirectMLPublish Include="$(PublishDir)runtimes\win-*\native\DirectML.dll" />
		</ItemGroup>
		<Delete Files="@(_UnusedDirectMLPublish)" />
	</Target>

</Project>
